In [3]:
import numpy as np
def calc_elevation(current_pos, map):
    current_val = map[current_pos[0],current_pos[1]]
    up_elevation = None if current_pos[1] == 0 else map[current_pos[0],current_pos[1]-1] - current_val
    down_elevation = None if current_pos[1] == map.shape[0] else map[current_pos[0],current_pos[1]+1] - current_val
    left_elevation = None if current_pos[0] == 0 else map[current_pos[0]-1,current_pos[1]] - current_val
    right_elevation = None if current_pos[0] == map.shape[0] else map[current_pos[0]+1,current_pos[1]] - current_val

    return current_val, up_elevation, down_elevation, left_elevation, right_elevation

def move(current_pos, end_pos, map):
    current_val, up_elevation, down_elevation, left_elevation, right_elevation = calc_elevation(current_pos, map)
    travel_distance = end_pos - current_pos
    print(travel_distance)
    
    
data = [list(line.strip()) for line in open("C:\git\AOC2020/2022\DATJA\day12test.txt", 'r')]
start_number = ord('S') - 96
end_number = ord('E') - 96
data = [[ord(x)-96 for x in y ]for y in data]
data = np.array(data)
print(data)

start_idx = np.where(data == start_number)
end_idx = np.where(data == end_number)



[[-13   1   2  17  16  15  14  13]
 [  1   2   3  18  25  24  24  12]
 [  1   3   3  19  26 -27  24  11]
 [  1   3   3  20  21  22  23  10]
 [  1   2   4   5   6   7   8   9]]
8
