In [26]:
def print_ele(test_list):
    new_list = []
    for ele in test_list:
        if ele < 0:
            new_list.append(ele)
        elif ele >= 0:
            new_list.append(ele)
            return len(new_list)
    return len(new_list)

import numpy as np
import itertools
data = [list(line.strip()) for line in open("C:\git\AOC2020/2022\DATJA\day8test.txt", 'r')]
data = [[int(x) for x in y ]for y in data]
data = np.array(data)
# print(data)
n_rows = len(data)
n_cols = len(data[0])
print(n_cols, n_rows)
n_visible_trees = 0
highest = 0
for tree_idx_col in range(1,n_cols-1):
    for tree_idx_row in range(1,n_rows-1):
        current_tree = data[tree_idx_row,tree_idx_col]
        # print('Tree index ', data[tree_idx_row,tree_idx_col])
        # above, left, right, below
        up, down = data[0:tree_idx_row,tree_idx_col], data[tree_idx_row+1::, tree_idx_col]
        left, right = data[tree_idx_row,0:tree_idx_col], data[tree_idx_row,tree_idx_col+1::]

        height_diff_up, height_diff_down, height_diff_left, height_diff_right = up - current_tree, down - current_tree, left - current_tree, right - current_tree
        sight_up, sight_down, sight_left, sight_right  = print_ele(height_diff_up[::-1]), print_ele(height_diff_down), print_ele(height_diff_left[::-1]), print_ele(height_diff_right)
        # print(up, down, left, right)
        # print(height_diff_up, height_diff_down, height_diff_left, height_diff_right)
        # print(sight_up, sight_down, sight_left, sight_right)
        total_sight = sight_up * sight_down * sight_left * sight_right
        if total_sight > highest:
            highest, idx = total_sight, [tree_idx_row,tree_idx_col]
        surrounding_trees = [up, left, right, down]
        if any(([all(i < current_tree) for i in surrounding_trees])):
           n_visible_trees += 1

print(n_visible_trees)
print(n_visible_trees + n_cols*2 + 2*n_rows -4)

print(highest, idx)

5 5
Tree index  5
[0] [5 3 5] [2] [5 1 2]
[-5] [ 0 -2  0] [-3] [ 0 -4 -3]
1 1 1 1
Tree index  5
[0 5] [3 5] [6] [3 3 2]
[-5  0] [-2  0] [1] [-2 -2 -3]
1 2 1 3
Tree index  3
[0 5 5] [5] [3] [5 4 9]
[-3  2  2] [2] [0] [2 1 6]
1 1 1 1
Tree index  5
[3] [3 5 3] [2 5] [1 2]
[-2] [-2  0 -2] [-3  0] [-4 -3]
1 2 1 2
Tree index  3
[3 5] [5 3] [6 5] [3 2]
[0 2] [2 0] [3 2] [ 0 -1]
1 1 1 1
Tree index  5
[3 5 3] [3] [3 3] [4 9]
[-2  0 -2] [-2] [-2 -2] [-1  4]
2 1 2 2
Tree index  1
[7] [3 4 9] [2 5 5] [2]
[6] [2 3 8] [1 4 4] [1]
1 1 1 1
Tree index  3
[7 1] [4 9] [6 5 3] [2]
[ 4 -2] [1 6] [3 2 0] [-1]
2 1 1 1
Tree index  4
[7 1 3] [9] [3 3 5] [9]
[ 3 -3 -1] [5] [-1 -1  1] [5]
3 1 1 1
5
21
8 [3, 2]
